CREATE OR REPLACE VIEW DISPLAYAPPOINTMENTCOUNT
AS SELECT DOCTORID, DNAME, SPECIALTY, COUNT(*) "NUMBEROFAPPOINTMENTS" FROM DOCTORS
JOIN APPOINTMENTS USING(DOCTORID)
GROUP BY DOCTORID, DNAME, SPECIALTY;

SELECT * FROM DISPLAYAPPOINTMENTCOUNT;

CREATE OR REPLACE PROCEDURE DELETECANCELLEDAPPOINTMENT
IS
BEGIN
    DELETE APPOINTMENTS
    WHERE SYSDATE - APPOINTMENTDATE > 7 AND STATUS = 'Cancelled';
    
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('There is NO cancelled appointments older than 7 days!');
    ELSE
        DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT || ' Cancelled appointments older than 7 days have been deleted.');
    END IF;
END;
/

SET SERVEROUTPUT ON;
BEGIN
    DELETECANCELLEDAPPOINTMENT();
END;
/

ROLLBACK;

DESC PATIENTS;

CREATE OR REPLACE FUNCTION CALCULATEAGE(INP_PATIENTID IN NUMBER) RETURN NUMBER
IS
    v_age NUMBER;
BEGIN
    SELECT TRUNC(MONTHS_BETWEEN(SYSDATE, BIRTHDATE) / 12) INTO v_age FROM PATIENTS
    WHERE PATIENTID = INP_PATIENTID;
        
    RETURN v_age;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        return -1;
END;
/

SET SERVEROUTPUT ON;
ACCEPT P_PATIENTID PROMPT 'Please enter the patient id';
DECLARE
    v_res NUMBER;
    p_patientId NUMBER := &P_PATIENTIDD;
BEGIN
    v_res := CALCULATEAGE(p_patientId);
    IF v_res = -1 THEN
        DBMS_OUTPUT.PUT_LINE('Patient with id ' || p_patientId || ' NOT FOUND!');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Age of the patient is: ' || v_res);
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE DOCTORAPPOINTMENTS
IS
    CURSOR doct_cursor IS
        SELECT DNAME, DOCTORID, COUNT(*) "TOTAL" FROM APPOINTMENTS
        JOIN DOCTORS USING (DOCTORID)
        JOIN PATIENTS USING (PATIENTID)
        GROUP BY DNAME, DOCTORID;
BEGIN
    FOR doct IN doct_cursor LOOP
        DBMS_OUTPUT.PUT_LINE('Doctor: ' || doct.DNAME);
        DBMS_OUTPUT.PUT_LINE('Number of Appointments: ' || doct.TOTAL);
        DBMS_OUTPUT.PUT_LINE('*******************');
        FOR appoint IN (
            SELECT * FROM APPOINTMENTS 
            JOIN PATIENTS USING(PATIENTID) 
            WHERE DOCTORID = doct.DOCTORID) 
        LOOP
            DBMS_OUTPUT.PUT_LINE('Appointment Info: ' || appoint.APPOINTMENTDATE || ' @' || appoint.APPOINTMENTTIME || ', ' || appoint.PNAME);
        END LOOP;
        DBMS_OUTPUT.PUT_LINE('-------------------');
        DBMS_OUTPUT.PUT_LINE('');
    END LOOP;
END;
/

BEGIN
    DOCTORAPPOINTMENTS();
END;
/

