SELECT LAST_NAME, JOB_ID, SALARY AS SAL FROM EMPLOYEES;

SELECT * FROM JOB_GRADES;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY * 12 "ANNUAL SALARY" FROM EMPLOYEES;

DESC DEPARTMENTS;
SELECT * FROM DEPARTMENTS;

DESC EMPLOYEES;

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, HIRE_DATE "STARTDATE" FROM EMPLOYEES;

SELECT DISTINCT JOB_ID FROM EMPLOYEES;

SELECT EMPLOYEE_ID "Emp #", LAST_NAME "Employee", JOB_ID "job", HIRE_DATE "Hire Date" FROM EMPLOYEES;

SELECT LAST_NAME || ', ' || JOB_ID "Employee and Title" FROM EMPLOYEES;

SELECT SYSDATE FROM DUAL;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, TRUNC(SALARY * 115.5 / 100) "New Salary" FROM EMPLOYEES;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, TRUNC(SALARY * 115.5 / 100) "New Salary", ROUND(SALARY * 115.5 / 100) - SALARY "Increase" FROM EMPLOYEES;

SELECT LAST_NAME "Name", LENGTH(LAST_NAME) FROM EMPLOYEES
WHERE SUBSTR(LAST_NAME, 1, 1) IN ('J', 'A', 'M');
SELECT LAST_NAME "Name", LENGTH(LAST_NAME) FROM EMPLOYEES
WHERE SUBSTR(LAST_NAME, 1, 1) = UPPER('&INITIAL_CHAR');

SELECT LAST_NAME, ROUND((SYSDATE - HIRE_DATE) / 30) "MONTHS_WORKED" FROM EMPLOYEES;






