CREATE TABLE PERSONNEL(
   ID   NUMBER(3)        NOT NULL,
   NAME VARCHAR2(20)     NOT NULL,
   SNAME VARCHAR2(20)    NOT NULL,
   AGE  INT              NOT NULL,
   ADDRESS  CHAR (25) ,
   SALARY   NUMBER (10, 2),       
   constraint personnel_pk PRIMARY KEY (ID)
);

desc PERSONNEL;

INSERT INTO PERSONNEL (ID,NAME,SNAME, AGE,ADDRESS,SALARY)
VALUES (1, 'Mike', 'Jones', 32, 'Newyork', 2750.00 );

INSERT INTO PERSONNEL (ID,NAME,SNAME, AGE,ADDRESS,SALARY)
VALUES (2, 'Daniel', 'Gonzales', 25, 'Rome', 3500.00 );

INSERT INTO PERSONNEL (ID,NAME,SNAME, AGE,ADDRESS,SALARY)
VALUES (3, 'Tommy', 'John', 23, 'London', 2000.00 );

INSERT INTO PERSONNEL (ID,NAME,SNAME, AGE,ADDRESS,SALARY)
VALUES (4, 'Daniel', 'Smith', 25, 'Istanbul', 6500.00 );

INSERT INTO PERSONNEL (ID,NAME,SNAME, AGE,ADDRESS,SALARY)
VALUES (5, 'Mark', 'Johnson', 38, 'California', 4850.00 );

INSERT INTO PERSONNEL (ID,NAME,SNAME, AGE,ADDRESS,SALARY)
VALUES (6, 'Maria', 'Rodrigez', 34, 'Ankara', 4500.00 );

commit;

select * from PERSONNEL;