SELECT E.LAST_NAME, E.FIRST_NAME, E.SALARY, D.DEPARTMENT_NAME FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT E.LAST_NAME, E.FIRST_NAME, E.SALARY FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.DEPARTMENT_NAME = 'Shipping';

DESC DEPARTMENTS;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, L.LOCATION_ID FROM DEPARTMENTS D, LOCATIONS L
WHERE D.LOCATION_ID = L.LOCATION_ID AND CITY = 'Seattle';

SELECT LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY > 12000;

SELECT LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES
WHERE EMPLOYEE_ID = 176;

SELECT LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY NOT BETWEEN 5000 AND 12000;

SELECT LAST_NAME, JOB_ID, HIRE_DATE FROM EMPLOYEES
WHERE LAST_NAME IN ('Matos', 'Taylor')
ORDER BY HIRE_DATE;

SELECT LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID BETWEEN 20 AND 50
ORDER BY LAST_NAME;

SELECT LAST_NAME "Employee", SALARY "Monthly Salary" FROM EMPLOYEES
WHERE (SALARY BETWEEN 5000 AND 12000) AND (DEPARTMENT_ID BETWEEN 20 AND 50);

SELECT LAST_NAME, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE LIKE '%94';
SELECT LAST_NAME, HIRE_DATE FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE, 'YYYY') = 1994;

SELECT LAST_NAME, JOB_ID FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

SELECT LAST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY COMMISSION_PCT DESC;

SELECT LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY > &INPUT_SALARY;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES
WHERE MANAGER_ID = &INPUT_MANAGER_ID
ORDER BY &SORT_COLUMN;

SELECT LAST_NAME FROM EMPLOYEES
WHERE LAST_NAME LIKE '__a%';

SELECT LAST_NAME FROM EMPLOYEES
WHERE LAST_NAME LIKE '%a%' AND LAST_NAME LIKE '%e%';

SELECT LAST_NAME, JOB_ID, SALARY FROM EMPLOYEES
WHERE JOB_ID IN ('SA_REP', 'ST_CLERK') AND SALARY NOT IN (2500, 3500, 7000);

SELECT LAST_NAME "Employee", SALARY "Monthly Salary", COMMISSION_PCT FROM EMPLOYEES
WHERE COMMISSION_PCT = 0.2;






