INSERT INTO RECEIPT (RID, RDATE, CID, TOTAL, PAYMENT_TYPE) 
VALUES (1, TO_DATE('07-OCT-25', 'DD-MON-RR'), 1, 72.80, 'VISA');

INSERT INTO RECEIPT (RID, RDATE, CID, TOTAL, PAYMENT_TYPE) 
VALUES (2, TO_DATE('07-NOV-25', 'DD-MON-RR'), 1, 17.01, 'CASH');

INSERT INTO RECEIPT (RID, RDATE, CID, TOTAL, PAYMENT_TYPE) 
VALUES (3, TO_DATE('10-SEP-25', 'DD-MON-RR'), 2, 34.80, 'VISA');

INSERT INTO RECEIPT (RID, RDATE, CID, TOTAL, PAYMENT_TYPE) 
VALUES (4, TO_DATE('15-AUG-25', 'DD-MON-RR'), 4, 59.30, 'VISA');

INSERT INTO RECEIPT (RID, RDATE, CID, TOTAL, PAYMENT_TYPE) 
VALUES (5, TO_DATE('08-NOV-25', 'DD-MON-RR'), 3, 38.70, 'VISA');

Insert into RECEIPT (RID,RDATE,CID,TOTAL,PAYMENT_TYPE) 
values (6,to_date('04-OCT-25','DD-MON-RR'),1,233.1,'VISA');

Insert into RECEIPT (RID,RDATE,CID,TOTAL,PAYMENT_TYPE) 
values (7,to_date('04-NOV-25','DD-MON-RR'),2,194.7,'VISA');

Insert into RECEIPT (RID,RDATE,CID,TOTAL,PAYMENT_TYPE) 
values (8,to_date('04-SEP-24','DD-MON-RR'),4,113.4,'VISA');
