SELECT LOCATION_ID, STREET_ADDRESS, CITY, STATE_PROVINCE, COUNTRY_NAME FROM LOCATIONS
NATURAL JOIN COUNTRIES;

SELECT LAST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME FROM EMPLOYEES
JOIN DEPARTMENTS USING(DEPARTMENT_ID);

SELECT LAST_NAME, JOB_ID, DEPARTMENT_ID, DEPARTMENT_NAME FROM EMPLOYEES
JOIN DEPARTMENTS USING(DEPARTMENT_ID)
JOIN LOCATIONS USING(LOCATION_ID)
WHERE CITY = 'Toronto';

SELECT e.LAST_NAME "Employee", e.EMPLOYEE_ID "EMP#", m.LAST_NAME "Manager",  m.EMPLOYEE_ID "Mgr#" FROM EMPLOYEES e
JOIN EMPLOYEES m ON m.EMPLOYEE_ID = e.MANAGER_ID;

SELECT e.LAST_NAME "Employee", e.EMPLOYEE_ID "EMP#", m.LAST_NAME "Manager",  m.EMPLOYEE_ID "Mgr#" FROM EMPLOYEES e
LEFT JOIN EMPLOYEES m ON m.EMPLOYEE_ID = e.MANAGER_ID;

SELECT e.DEPARTMENT_ID "DEPARTMENT", e.LAST_NAME "EMPLOYEE", c.LAST_NAME "COLLEAGUE" FROM EMPLOYEES e
JOIN EMPLOYEES c ON e.DEPARTMENT_ID = c.DEPARTMENT_ID
WHERE e.EMPLOYEE_ID <> c.EMPLOYEE_ID
ORDER BY e.DEPARTMENT_ID, e.LAST_NAME;

SELECT LAST_NAME, JOB_ID, DEPARTMENT_NAME, SALARY, GRADE_LEVEL FROM EMPLOYEES e
JOIN JOB_GRADES ON SALARY BETWEEN LOWEST_SAL AND HIGHEST_SAL
JOIN DEPARTMENTS d USING(DEPARTMENT_ID);

SELECT e.LAST_NAME, e.HIRE_DATE, m.LAST_NAME, m.HIRE_DATE FROM EMPLOYEES e
JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID
WHERE m.HIRE_DATE > e.HIRE_DATE
ORDER BY m.HIRE_DATE;