CREATE TABLE DEPT2 (
    ID NUMBER(7),
    NAME VARCHAR(25)
);

INSERT INTO DEPT2
SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM DEPARTMENTS;

CREATE TABLE EMP2 (
    ID NUMBER(7),
    LAST_NAME VARCHAR2(25),
    FIRST_NAME VARCHAR2(25),
    DEPT_ID NUMBER(7)
);

ALTER TABLE EMP2
MODIFY LAST_NAME VARCHAR2(50);

CREATE TABLE EMPLOYEES2 AS
SELECT EMPLOYEE_ID ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID DEPT_ID FROM EMPLOYEES;

DROP TABLE EMP2;

SELECT * FROM RECYCLEBIN;

FLASHBACK TABLE EMP2 TO BEFORE DROP;

ALTER TABLE EMPLOYEES2
DROP COLUMN FIRST_NAME;
DESC EMPLOYEES2;

ALTER TABLE EMPLOYEES2
SET UNUSED COLUMN DEPT_ID;
DESC EMPLOYEES2;

ALTER TABLE EMPLOYEES2
DROP UNUSED COLUMNS;
DESC EMPLOYEES2;

ALTER TABLE EMP2
ADD CONSTRAINT my_emp_id_pk PRIMARY KEY(ID);

ALTER TABLE DEPT2
ADD CONSTRAINT my_dept_id_pk PRIMARY KEY(ID);

ALTER TABLE EMP2
ADD CONSTRAINT my_emp_dept_id_fk FOREIGN KEY(ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID) ON DELETE CASCADE;

ALTER TABLE EMP2
ADD COMMISSION NUMBER(2, 2) CONSTRAINT check_commission CHECK (COMMISSION > 0);

DROP TABLE EMP2 PURGE;
DROP TABLE DEPT2 PURGE;
SELECT * FROM RECYCLEBIN;

CREATE TABLE EMPLOYEES3 AS
SELECT EMPLOYEE_ID ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID DEPT_ID FROM EMPLOYEES;

ALTER TABLE EMPLOYEES3 READ ONLY;

INSERT INTO EMPLOYEES3(FIRST_NAME, LAST_NAME, SALARY, DEPT_ID) VALUES ('Grant', 'Marcie', 5678, 10);

ALTER TABLE EMPLOYEES3 READ WRITE;
INSERT INTO EMPLOYEES3(FIRST_NAME, LAST_NAME, SALARY, DEPT_ID) VALUES ('Grant', 'Marcie', 5678, 10);

DROP TABLE EMPLOYEES3;




