SELECT MAX(SALARY), MIN(SALARY), SUM(SALARY), AVG(SALARY) FROM EMPLOYEES;

SELECT JOB_ID, MAX(SALARY), MIN(SALARY), SUM(SALARY), ROUND(AVG(SALARY), 0) FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_ID, COUNT(*) FROM EMPLOYEES
WHERE JOB_ID = '&JOBID_INP'
GROUP BY JOB_ID;

SELECT COUNT(DISTINCT MANAGER_ID) "Number of Managers" FROM EMPLOYEES;

SELECT (MAX(SALARY) - MIN(SALARY)) "Difference" FROM EMPLOYEES;

SELECT MANAGER_ID, MIN(SALARY) FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID
HAVING MIN(SALARY) > 6000
ORDER BY MIN(SALARY) DESC;

SELECT 
COUNT(*),
SUM(DECODE(TO_CHAR(HIRE_DATE, 'YYYY'), 1995, 1, 0)) "1995",
SUM(DECODE(TO_CHAR(HIRE_DATE, 'YYYY'), 1996, 1, 0)) "1996",
SUM(DECODE(TO_CHAR(HIRE_DATE, 'YYYY'), 1997, 1, 0)) "1997",
SUM(DECODE(TO_CHAR(HIRE_DATE, 'YYYY'), 1998, 1, 0)) "1998"
FROM EMPLOYEES;

SELECT 
JOB_ID "Job",
SUM(DECODE(DEPARTMENT_ID, 20, SALARY)) "Dept 20",
SUM(DECODE(DEPARTMENT_ID, 50, SALARY)) "Dept 50",
SUM(DECODE(DEPARTMENT_ID, 80, SALARY)) "Dept 80",
SUM(DECODE(DEPARTMENT_ID, 90, SALARY)) "Dept 90",
SUM(SALARY) "Total"
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT LAST_NAME, DEPARTMENT_ID, SALARY FROM EMPLOYEES
WHERE (DEPARTMENT_ID, SALARY) IN (SELECT DEPARTMENT_ID, SALARY FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL);

SELECT LAST_NAME, DEPARTMENT_NAME, SALARY FROM EMPLOYEES e
JOIN DEPARTMENTS d USING(DEPARTMENT_ID)
WHERE (SALARY, NVL(COMMISSION_PCT, 0)) IN (SELECT SALARY, NVL(COMMISSION_PCT, 0) FROM EMPLOYEES WHERE d.LOCATION_ID = 1700);

SELECT LAST_NAME, HIRE_DATE, SALARY FROM EMPLOYEES
WHERE (SALARY, NVL(COMMISSION_PCT, 0)) = (SELECT SALARY, NVL(COMMISSION_PCT, 0) FROM EMPLOYEES WHERE LAST_NAME = 'Kochhar')
AND LAST_NAME <> 'Kochhar';

SELECT LAST_NAME, JOB_ID, SALARY FROM EMPLOYEES e
WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES w WHERE JOB_ID = 'SA_MAN')
ORDER BY SALARY DESC;

SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES e
JOIN DEPARTMENTS d USING(DEPARTMENT_ID)
JOIN LOCATIONS l USING(LOCATION_ID)
WHERE CITY LIKE 'T%';

SELECT 
e.LAST_NAME "ENAME",
e.SALARY,
e.DEPARTMENT_ID "DEPTNO",
ROUND(AVG(aemp.SALARY)) "DEPT_AVG"
FROM EMPLOYEES e, EMPLOYEES aemp
WHERE e.DEPARTMENT_ID = aemp.DEPARTMENT_ID
GROUP BY e.LAST_NAME, e.SALARY, e.DEPARTMENT_ID
HAVING e.SALARY > AVG(aemp.SALARY)
ORDER BY AVG(aemp.SALARY);

SELECT e.LAST_NAME FROM EMPLOYEES e
WHERE NOT EXISTS (SELECT * FROM EMPLOYEES m WHERE e.EMPLOYEE_ID = m.MANAGER_ID);

SELECT e.LAST_NAME FROM EMPLOYEES e
WHERE e.EMPLOYEE_ID NOT IN (SELECT NVL(MANAGER_ID, -1) FROM EMPLOYEES);

SELECT LAST_NAME FROM EMPLOYEES e
WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES c WHERE e.DEPARTMENT_ID = c.DEPARTMENT_ID);

SELECT LAST_NAME FROM EMPLOYEES e
WHERE SALARY < ANY (SELECT SALARY FROM EMPLOYEES c WHERE e.DEPARTMENT_ID = c.DEPARTMENT_ID AND e.HIRE_DATE < c.HIRE_DATE);
SELECT LAST_NAME FROM EMPLOYEES e
WHERE EXISTS (SELECT * FROM EMPLOYEES c WHERE e.DEPARTMENT_ID = c.DEPARTMENT_ID AND e.HIRE_DATE < c.HIRE_DATE AND e.SALARY < c.SALARY);

SELECT EMPLOYEE_ID, LAST_NAME, (SELECT DEPARTMENT_NAME FROM DEPARTMENTS d WHERE d.DEPARTMENT_ID = e.DEPARTMENT_ID) "DEPARTMENT" FROM EMPLOYEES e;





