SELECT LAST_NAME || ' earns' || TO_CHAR(SALARY, '$99,000.00') || ' monthly but wants' || TO_CHAR(SALARY, '$99,000.00') || '.' "Dream Salary" FROM EMPLOYEES;

SELECT LAST_NAME, HIRE_DATE, TO_CHAR(NEXT_DAY(ADD_MONTHS(HIRE_DATE, 6), 'MONDAY'), 'fmDay, "the" Ddspth "of" month YYYY') "REVIEW" FROM EMPLOYEES;

SELECT LAST_NAME, HIRE_DATE, TO_CHAR(HIRE_DATE, 'Day') "DAY" FROM EMPLOYEES
ORDER BY TO_CHAR(HIRE_DATE, 'D');

SELECT LAST_NAME, NVL(TO_CHAR(COMMISSION_PCT), 'No Commission') FROM EMPLOYEES;

SELECT 
JOB_ID, 
DECODE(
    JOB_ID,
    'AD_PRES', 'A',
    'ST_MAN', 'B',
    'IT_PROG', 'C',
    'SA_REP', 'D',
    'ST_CLERK', 'E',
    '0'
) "GRADE" 
FROM EMPLOYEES;

SELECT 
JOB_ID, 
CASE JOB_ID
WHEN 'AD_PRES' THEN 'A'
WHEN 'ST_MAN' THEN 'B'
WHEN 'IT_PROG' THEN 'C'
WHEN 'SA_REP' THEN 'D'
WHEN 'ST_CLERK' THEN 'E'
ELSE '0' END "GRADE" 
FROM EMPLOYEES;

SELECT BDATE, ADDRESS FROM EMPLOYEE
WHERE FNAME = 'JOHN' AND LNAME = 'MICC';

SELECT * FROM EMPLOYEE
WHERE DNO = 1;

SELECT DISTINCT ADDRESS FROM EMPLOYEE;

SELECT * FROM EMPLOYEE
WHERE DNO = 1 AND SALARY BETWEEN 10000 AND 15000;

SELECT d.DNAME, e.LNAME, e.FNAME, p.PNAME FROM EMPLOYEE e 
JOIN DEPARTMENT d ON d.DNUMBER = E.DNO 
JOIN WORKS_ON w ON e.SSN = w.ESSN 
JOIN PROJECT p ON w.PNO = p.PNUMBER 
ORDER BY d.DNAME, e.LNAME, e.FNAME;

SELECT FNAME, LNAME, ADDRESS FROM EMPLOYEE e
JOIN DEPARTMENT d ON d.DNUMBER = e.DNO
WHERE d.DNAME = 'RESEARCH';

SELECT 
    p.PNUMBER, 
    d.DNUMBER, 
    e.LNAME, 
    e.ADDRESS, 
    e.BDATE
FROM PROJECT p
JOIN DEPARTMENT d ON p.DNUM = d.DNUMBER
JOIN EMPLOYEE e ON d.MGRSSN = e.SSN
WHERE p.PLOCATION = 'HOUSTON';


























