SELECT SSN FROM EMPLOYEE e
WHERE NOT EXISTS (SELECT * FROM DEPENDENT d WHERE e.SSN = d.ESSN)
ORDER BY SSN;
SELECT SSN FROM EMPLOYEE
MINUS
SELECT ESSN FROM DEPENDENT
ORDER BY SSN;

SELECT SSN FROM EMPLOYEE e
WHERE EXISTS (SELECT * FROM DEPENDENT d WHERE e.SSN = d.ESSN)
ORDER BY SSN;
SELECT SSN FROM EMPLOYEE
INTERSECT
SELECT ESSN FROM DEPENDENT;

SELECT SSN FROM EMPLOYEE
UNION ALL
SELECT MGRSSN FROM DEPARTMENT;

SELECT SSN FROM EMPLOYEE
MINUS
SELECT MGRSSN FROM DEPARTMENT;

SELECT SSN FROM EMPLOYEE
INTERSECT
SELECT MGRSSN FROM DEPARTMENT;

SELECT DNUM "DEPT_NUMBER" FROM PROJECT
INTERSECT
SELECT DNUMBER FROM DEPARTMENT;

SELECT DNUMBER FROM DEPARTMENT
MINUS
SELECT DNUM "DEPT_NUMBER" FROM PROJECT;

SELECT SSN, FNAME, LNAME, PNAME, PLOCATION FROM EMPLOYEE e
LEFT JOIN PROJECT p ON p.DNUM = e.DNO;

SELECT SSN, FNAME, LNAME, DNO, PNUMBER, PNAME, PLOCATION, DNUM FROM EMPLOYEE e
FULL JOIN PROJECT p ON p.DNUM = e.DNO;

UNDEFINE LASTNAME_INP;
SELECT LAST_NAME, HIRE_DATE FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME = '&&LASTNAME_INP')
AND LAST_NAME <> '&LASTNAME_INP';

SELECT EMPLOYEE_ID, LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY > (SELECT SALARY FROM EMPLOYEES WHERE LAST_NAME = 'Taylor')
ORDER BY SALARY;

SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME LIKE '%u%');

SELECT LAST_NAME, DEPARTMENT_ID, JOB_ID FROM EMPLOYEES e
JOIN DEPARTMENTS d USING (DEPARTMENT_ID)
WHERE d.LOCATION_ID = &LOCATION_ID_INP;

SELECT w.LAST_NAME, w.SALARY FROM EMPLOYEES w
JOIN EMPLOYEES m ON m.EMPLOYEE_ID = w.MANAGER_ID
WHERE m.LAST_NAME = 'King';

SELECT DEPARTMENT_ID, LAST_NAME, JOB_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'Executive');

SELECT EMPLOYEE_ID, LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY > (SELECT SALARY FROM EMPLOYEES WHERE LAST_NAME = 'Taylor')
AND DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME LIKE '%g%');

SELECT LAST_NAME FROM EMPLOYEES
WHERE SALARY > ANY(SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 60);








