SELECT s.STNAME, s.STSURNAME, sc.GRADE, CNAME FROM STUDENT s
JOIN STUCOURSE sc ON sc.STU_ID = s.STUID
JOIN COURSE co ON co.CCODE = sc.C_CODE
WHERE sc.sem = 162;

SELECT * FROM STUCOURSE;
SELECT STNAME, STSURNAME, COUNT(STUID) FROM STUDENT
WHERE EXISTS (SELECT STU_ID FROM STUCOURSE HAVING (COUNT(STU_ID) > 2) GROUP BY STU_ID)
GROUP BY STUID;

SELECT CNAME FROM COURSE
WHERE NOT EXISTS(SELECT * FROM STUCOURSE WHERE GRADE='A' AND C_CODE=CCODE);

SELECT STNAME, STSURNAME FROM STUDENT
WHERE NOT EXISTS (SELECT * FROM SEMESTER WHERE STANDING IN ('HONOUR', 'HIGH HONOUR'));

SELECT CNAME, COUNT(*) FROM STUCOURSE st
JOIN COURSE c ON c.CCODE = st.C_CODE
GROUP BY CNAME
HAVING COUNT(*) > 1;

SELECT CNAME, COUNT(*) FROM STUCOURSE st
JOIN COURSE c ON c.CCODE = st.C_CODE
JOIN SEMESTER s ON s.SID = st.STU_ID
WHERE STANDING = 'HIGH HONOUR'
GROUP BY CNAME
HAVING COUNT(*) > 1;

SELECT STNAME, STSURNAME FROM STUDENT
WHERE CGPA > (SELECT AVG(CGPA) FROM STUDENT);

SELECT COUNT(*) "HONOUR_NUMBER", STNAME  FROM STUDENT s
JOIN SEMESTER sm ON sm.SID = s.STUID
WHERE STANDING = 'HONOUR'
GROUP BY STNAME
HAVING COUNT(*) > 1;

---

SELECT ALBUMTITLE, ARTISTNAME FROM ALBUMS a
JOIN ARTISTS ar USING (ARTISTID)
WHERE RELEASEYEAR = 2023;

SELECT ARTISTNAME FROM ARTISTS
WHERE GENRE IN ('Rock', 'Pop');
SELECT DISTINCT ARTISTNAME FROM ALBUMS a
JOIN ARTISTS ar USING (ARTISTID)
WHERE EXISTS (SELECT GENRE FROM SONGS s WHERE s.ALBUMID = a.ALBUMID AND GENRE IN ('Rock', 'Pop'));

SELECT ALBUMTITLE, COUNT(*) FROM ALBUMS
JOIN SONGS s USING (ALBUMID)
GROUP BY ALBUMTITLE;

SELECT ALBUMTITLE, SUM(ALBUMPRICE * QUANTITY) "TOTALSALESAMOUNT" FROM ALBUMS
JOIN ORDERITEMS USING(ALBUMID)
GROUP BY ALBUMTITLE;

SELECT GENRE, SUM(ALBUMPRICE * QUANTITY) "TOTALSALESAMOUNT" FROM ALBUMS
JOIN SONGS USING (ALBUMID)
JOIN ORDERITEMS USING(ALBUMID)
GROUP BY GENRE;

SELECT DISTINCT FIRSTNAME, LASTNAME FROM CUSTOMERS
JOIN ORDERS USING(CUSTOMERID)
WHERE ORDERDATE LIKE '%23';

SELECT GENRE, ROUND(AVG(ALBUMPRICE), 2) "AVGALBUMPRICE" FROM ALBUMS
JOIN SONGS USING(ALBUMID)
GROUP BY GENRE;

SELECT ALBUMTITLE, SUM(QUANTITY) "TOTALQUANTITYSOLD" FROM ALBUMS
JOIN ORDERITEMS USING (ALBUMID)
GROUP BY ALBUMTITLE
HAVING SUM(QUANTITY) > 2;

SELECT FIRSTNAME, LASTNAME, COUNT(*) "TOTALPURCHASES" FROM CUSTOMERS
JOIN ORDERS USING (CUSTOMERID)
GROUP BY FIRSTNAME, LASTNAME
HAVING COUNT(FIRSTNAME) > 1;

SELECT ALBUMID, ALBUMTITLE FROM ALBUMS
MINUS
SELECT ALBUMID, ALBUMTITLE FROM ALBUMS
JOIN ORDERITEMS USING(ALBUMID);

SELECT ARTISTNAME, SUM(ALBUMPRICE * QUANTITY) "TOTALREVENUE" FROM ARTISTS
JOIN ALBUMS USING (ARTISTID)
JOIN ORDERITEMS USING (ALBUMID)
GROUP BY ARTISTNAME;

SELECT ARTISTNAME,
       SUM(ALBUMPRICE * QUANTITY) AS TOTALREVENUE
FROM ARTISTS
JOIN ALBUMS USING (ARTISTID)
JOIN ORDERITEMS USING (ALBUMID)
GROUP BY ARTISTNAME
HAVING SUM(ALBUMPRICE * QUANTITY) >
       (
         SELECT SUM(ALBUMPRICE * QUANTITY)
         FROM ARTISTS
         JOIN ALBUMS USING (ARTISTID)
         JOIN ORDERITEMS USING (ALBUMID)
         WHERE ARTISTNAME = 'Emily White'
       );

SELECT FIRSTNAME, LASTNAME, SUM(TOTALAMOUNT) "TOTALSPENT" FROM CUSTOMERS
JOIN ORDERS USING(CUSTOMERID)
GROUP BY FIRSTNAME, LASTNAME;

SELECT FIRSTNAME, LASTNAME FROM CUSTOMERS
JOIN ORDERS USING(CUSTOMERID)
GROUP BY FIRSTNAME, LASTNAME
HAVING SUM(TOTALAMOUNT) > (SELECT AVG(TOTALAMOUNT) FROM ORDERS);

SELECT DISTINCT ARTISTNAME FROM ALBUMS a
JOIN ARTISTS ar USING (ARTISTID)
WHERE EXISTS (SELECT GENRE FROM SONGS s WHERE s.ALBUMID = a.ALBUMID AND GENRE IN ('Rock', 'Pop'));